project:
  type: website

website:
  title: "ISSS626-GAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu: 
          - text: "Geospatial Data Wrangling with R" 
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01a.html"
          - text: "Choropleth Mapping with R" 
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01b.html"
    right:
      - href: index.qmd
        text: Home
      - href: about.qmd
        text: About
      
format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

