project:
  type: website

website:
  title: "ISSS626-GAA"
  navbar:
    left:
      - text: "Hands-on Exercise"
        menu: 
          - text: "Geospatial Data Wrangling with R" 
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01a.html"
          - text: "Choropleth Mapping with R" 
            href: "Hands-on_Ex/Hands-on_Ex01/Hands-on_Ex01b.html"
          - text: "1st Order Spatial Points Patterns Analysis Methods" 
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02a.html"
          - text: "2nd Order Spatial Points Patterns Analysis Methods"
            href: "Hands-on_Ex/Hands-on_Ex02/Hands-on_Ex02b.html"

    right:
      - href: index.qmd
        text: Home
      
format:
  html:
    theme:
      - minty
      - brand
    css: styles.css
    toc: true

editor: visual

